***

# Numpy Arrays

https://numpy.org 

https://numpy.org/doc/stable/user/quickstart.html 

In [1]:
import numpy as np

# numpy arrays are homogeneous (the same type), unlike lists and tuples

# creating a numpy array from a list
a = np.array([1., 2., 3., 4., 5.])
print(a)
print(type(a))
print(type(a[0]))

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


### Numpy Array Types

In [2]:
# numpy arrays can have a wide range of types

a = np.array([1, 2, 3, 4, 5], dtype='int64')

print(a)
print(type(a))
print(type(a[0]))
print(a.dtype)
print()

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.int64'>
int64



In [3]:
# numpy arrays can have a wide range of types

b = np.array([1, 2, 3, 4, 5], dtype='float64')

print(b)
print(type(b))
print(type(b[0]))
print(b.dtype)
print()

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>
float64



In [4]:
# numpy arrays can have a wide range of types

c = np.array([1, 2, 3, 4, 5], dtype='uint8')

print(c)
print(type(c))
print(type(c[0]))
print(c.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.uint8'>
uint8


### Multidimensional Numpy Arrays

In [5]:
# multidimensional numpy arrays

# this is a list
a = [[1, 2, 3], [4, 5, 6]]

# convert to a numpy array
b = np.array(a)

print(a)
print(b)

# can also start with a tuple
a = ((1, 2, 3), (4, 5, 6))

# convert to a numpy array
b = np.array(a)

print(a)
print(b)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
((1, 2, 3), (4, 5, 6))
[[1 2 3]
 [4 5 6]]


### Lists vs. Numpy Arrays

In [6]:
# lists vs. numpy arrays

a = [[1, 2, 3], [4, 5, 6]]
b = np.array(a)

# addressing lists vs. numpy arrays
print("a[1][2] ", a[1][2])
print("b[1,2]  ", b[1,2])

a[1][2]  6
b[1,2]   6


In [7]:
# this is perfectly ok with a list
a = [[1, 2], [4, 5, 6]]
print(a)

# doesn't work with a numpy array
b = np.array(a)
print(b)

[[1, 2], [4, 5, 6]]
[list([1, 2]) list([4, 5, 6])]


/var/folders/cn/2ndxgmyd0s51q8_w0mfv_bhw0000gn/T/ipykernel_19952/3331529252.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.array(a)


### Shapes of Numpy Arrays

In [8]:
import numpy as np

# shape of numpy array
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)
s = a.shape
print("a.shape : ", s)
type(s)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
a.shape :  (4, 2)


tuple

In [9]:
b = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
print(b)
c = np.array(b)
print(c)
print(c.shape)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


### Slicing Numpy Arrays

In [10]:
# slicing numpy arrays (see class slides for illustrations)

import numpy as np

a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(a[0,:,:])
print(a[:,1,:])
print(a[:,:,1])

[[1 2 3]
 [4 5 6]]
[[ 4  5  6]
 [10 11 12]]
[[ 2  5]
 [ 8 11]]


In [11]:
# slicing part of a numpy array

a = np.array([[1, 1, 2, 2, 3, 3, 4, 4, 5, 5], [6, 6, 7, 7, 8, 8, 9, 9, 0, 0]])
print(a)

[[1 1 2 2 3 3 4 4 5 5]
 [6 6 7 7 8 8 9 9 0 0]]


In [12]:
print("a[0, 2:7]")
print(a[0, 2:7])

a[0, 2:7]
[2 2 3 3 4]


In [13]:
print("a[:, 5:]")
print(a[:, 5:])

a[:, 5:]
[[3 4 4 5 5]
 [8 9 9 0 0]]


In [14]:
print("a[1, 0:10:2]")
print(a[1, 0:10:2])

a[1, 0:10:2]
[6 7 8 9 0]


In [15]:
print("a[:, [9, 4, 6]]")
print(a[:, [9, 4, 6]])

a[:, [9, 4, 6]]
[[5 3 4]
 [0 8 9]]


### Preallocating Numpy Arrays

In [16]:
# preallocating numpy arrays with zeros

import numpy as np

a = np.zeros(5)
print(a)
print(a.shape)

# is the same as
a = np.zeros((5,))
print(a)
print(a.shape)

[0. 0. 0. 0. 0.]
(5,)
[0. 0. 0. 0. 0.]
(5,)


In [17]:
# can specify type
a = np.zeros(5, dtype=int)
print(a)
b = np.zeros(5, dtype=float)
print(b)

[0 0 0 0 0]
[0. 0. 0. 0. 0.]


In [18]:
# multidimensional numpy array

a = np.zeros((4,3))
print(a)
(r,c) = a.shape
print(r,c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
4 3


In [19]:
# preallocating with ones

a = np.ones((5,))
print(a)
print(a.shape)

[1. 1. 1. 1. 1.]
(5,)


In [20]:
# note these differences

# array of 5 elements (1D vector)
a = np.ones((5,))
print(a)
print(a.shape)
print()

# 2D column vector
b = np.ones((5,1))
print(b)
print(b.shape)
print()

# 2D row vector
c = np.ones((1,5))
print(c)
print(c.shape)

[1. 1. 1. 1. 1.]
(5,)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(5, 1)

[[1. 1. 1. 1. 1.]]
(1, 5)


In [21]:
# fill a numpy array with a sequence

# min, max, step (doesn't include max)
a = np.arange(0, 10, .1)
print(a)

# min, max, number of equal-spaced elements (includes max)
b = np.linspace(0, 10, 100)
print(b)

c = np.linspace(0, 10, 101)
print(c)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848

In [22]:
# fill with (uniformly-distributed) random numbers 
# (we will talk more about random numbers later)

a = np.random.random((5, 4))
print(a)

[[0.8068114  0.38670721 0.36305956 0.52768024]
 [0.24227015 0.22022674 0.10703583 0.54545592]
 [0.85120612 0.13414019 0.43938607 0.01259818]
 [0.03268108 0.4094064  0.58956313 0.72056486]
 [0.60121489 0.04738853 0.90205803 0.69638752]]


### Extending, Reshaping, Resizing Numpy Arrays

In [23]:
# extend a numpy array (using append)

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(f"a: (nrows, ncols) = ({a.shape[0]}, {a.shape[1]})")
print(a)

a: (nrows, ncols) = (2, 3)
[[1 2 3]
 [4 5 6]]


In [24]:
# add a new row
b = np.array([[7, 8, 9]])
print(f"b: (nrows, ncols) = ({b.shape[0]}, {b.shape[1]})")
c = np.append(a, b, axis=0)
print(c)

b: (nrows, ncols) = (1, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(a)

[[1 2 3]
 [4 5 6]]


In [26]:
# add a new row of zeros
b = np.zeros((1, a.shape[1]), dtype=a.dtype)
print(f"b: (nrows, ncols) = ({b.shape[0]}, {b.shape[1]})")
c = np.append(a, b, axis=0)
print(c)

b: (nrows, ncols) = (1, 3)
[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [27]:
# add 5 new columns of zeros
b = np.zeros((a.shape[0], 5))
print(f"b: (nrows, ncols) = ({b.shape[0]}, {b.shape[1]})")
c = np.append(a, b, axis=1)
print(c)

b: (nrows, ncols) = (2, 5)
[[1. 2. 3. 0. 0. 0. 0. 0.]
 [4. 5. 6. 0. 0. 0. 0. 0.]]


In [28]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[6, 7], [8, 9]])

# can append to axis 0 OR axis 1

c = np.append(a, b, axis=1)

print(a)
print(b)
print(c)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[1 2 6 7]
 [3 4 8 9]]


In [29]:
# extend a numpy array (using concatenate)

a = np.array([[1, 2, 3], [4, 5, 6]])
print(f"a: (nrows, ncols) = ({a.shape[0]}, {a.shape[1]})")
print(a)

a: (nrows, ncols) = (2, 3)
[[1 2 3]
 [4 5 6]]


In [30]:
# add a new row
b = np.array([[7, 8, 9]])
print(f"b: (nrows, ncols) = ({b.shape[0]}, {b.shape[1]})")
c = np.concatenate((a, b), axis=0)
print(c)

b: (nrows, ncols) = (1, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
# add a new row of zeros
b = np.zeros((1, a.shape[1]), dtype=a.dtype)
print(f"b: (nrows, ncols) = ({b.shape[0]}, {b.shape[1]})")
c = np.concatenate((a, b), axis=0)
print(c)

b: (nrows, ncols) = (1, 3)
[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [32]:
# add 5 new columns of zeros
b = np.zeros((a.shape[0], 5))
print(f"b: (nrows, ncols) = ({b.shape[0]}, {b.shape[1]})")
c = np.concatenate((a, b), axis=1)

b: (nrows, ncols) = (2, 5)


In [34]:
# unlike append, concatenate can do multiples

c = np.concatenate((a, b, a, b), axis=1)
print(c)

[[1. 2. 3. 0. 0. 0. 0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]
 [4. 5. 6. 0. 0. 0. 0. 0. 4. 5. 6. 0. 0. 0. 0. 0.]]


In [35]:
# for both append and concatenate, the axes need to make sense

print(a.shape)
print(b.shape)
c = np.concatenate((a, b, a, b), axis=0)
print(c)

(2, 3)
(2, 5)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [36]:
# reshape/resize numpy array

a = np.array([[1, 2, 3], [4, 5, 6]])
(nr, nc) = a.shape

In [37]:
# reshape (keep a the same)
b = a.reshape((1, nr*nc))
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


In [38]:
b = a.reshape((nr*nc, 1))
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [39]:
b = a.reshape((1, 1, nr*nc, 1, 1))
print(a)
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
[[[[[1]]

   [[2]]

   [[3]]

   [[4]]

   [[5]]

   [[6]]]]]
(1, 1, 6, 1, 1)


In [40]:
b = a.reshape((nr*nc,))
print(a)
print(b)
print(a.shape)
print(b.shape)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
(2, 3)
(6,)


In [41]:
# resize (changes a, doesn't return a new array)
b = a.resize((nc, nr))
print(a)
print(b)

[[1 2]
 [3 4]
 [5 6]]
None


In [42]:
# transpose rows and columns

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)
print()

print(a.transpose())
print()

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]



### Delete Indices, Rows, Columns in Numpy Array

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [43]:
# delete part of a numpy array

import numpy as np

a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# delete a single index position
b = np.delete(a, 2)
print(b)

# delete a range of index positions
b = np.delete(a, range(1,4))
print(b)

# delete a list of index positions
b = np.delete(a, [1, 5, 7])
print(b)

[10 20 40 50 60 70 80 90]
[10 50 60 70 80 90]
[10 30 40 50 70 90]


In [ ]:
# delete rows and columns - first create a 3D numpy array

a = (np.arange(100)).reshape((4, 5, 5))
print(a.shape)
print(a)

In [ ]:
# note that "row" refers to the first part of array, not what's displayed
print(a[2,:,:])

In [ ]:
# delete third "row" (axis=0)
b = np.delete(a, 2, axis=0)
print(b)

In [ ]:
# note that "col" refers to the second part of array, not what's displayed
print(a[:,1,:])

In [ ]:
# delete second column (axis=1)
b = np.delete(a, 1, axis=1)
print(b)

In [ ]:
# note that "page" refers to the third part of array, not what's displayed
print(a[:,:,0])

In [ ]:
# delete first page (axis=2)
b = np.delete(a, 0, axis=2)
print(b)

### Copying Numpy Arrays

these are not copies of numpy array

In [44]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a
c = a[:, 1:]
print(a)
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [45]:
a[1,2] = 99
print(a)
print(b)
print(c)

[[ 1  2  3]
 [ 4  5 99]]
[[ 1  2  3]
 [ 4  5 99]]
[[ 2  3]
 [ 5 99]]


In [46]:
b[0,1] = 66
print(a)
print(b)
print(c)

[[ 1 66  3]
 [ 4  5 99]]
[[ 1 66  3]
 [ 4  5 99]]
[[66  3]
 [ 5 99]]


copy (will copy all numeric elements)

In [47]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.copy()
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [48]:
a[1,2] = 99
print(a)
print(b)

[[ 1  2  3]
 [ 4  5 99]]
[[1 2 3]
 [4 5 6]]


In [49]:
b[0,1] = 66
print(a)
print(b)

[[ 1  2  3]
 [ 4  5 99]]
[[ 1 66  3]
 [ 4  5  6]]


note this

In [50]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a[:, 1:]
c = a[:, [2,1]]
print(a)
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[3 2]
 [6 5]]


In [51]:
# this is a view
b[1, 1] = 99
print(a)
print(b)
print(c)

[[ 1  2  3]
 [ 4  5 99]]
[[ 2  3]
 [ 5 99]]
[[3 2]
 [6 5]]


In [52]:
# this is a copy
c[1, 1] = 77
print(a)
print(b)
print(c)

[[ 1  2  3]
 [ 4  5 99]]
[[ 2  3]
 [ 5 99]]
[[ 3  2]
 [ 6 77]]


in this case, part of a is copied into part of b

In [ ]:
a = np.array([[1, 2, 3, 5], [4, 5, 6, 7]])
b = np.array([[8, 8, 8, 8], [9, 9, 9, 9]])
b[:,2:] = a[:,2:]

print(a)
print(b)

In [ ]:
a[0, 3] = 99
b[0, 3] = 55
print(a)
print(b)
print()

In [2]:
x = 3.9
int(x)

3